version: 2

sources:
  - name: comercial
    description: Banco exercicio curso. Mart de vendas.
    schema: dbt_rura
    tables:
      - name: stg_erp__ordens
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados.
        columns:
          - name: id_ordem
            description: Chave primária da tabela de ordens.
            tests:
              - unique
              - not_null
      
      - name: stg_erp__ordens_itens
        description: Tabela de itens das ordens.
        columns:
          - name: id_ordem
            description: Chave primária da tabela de ordens.
            #tests:
              #- not_null
          - name: product_id
            description: Chave primária da tabela de produtos.
            #tests:
              #- not_null

      - name: stg_erp__categorias

      - name: stg_erp__clientes

      - name: stg_erp__emrpegados_territorios

      - name: stg_erp__empregados

      - name: stg_erp__fornecedores

      - name: stg_erp__produtos

      - name: stg_erp__transportadoras

